### ISSUE TITLE
New Search and Profile Component.

### ISSUE THREAD

**Issue by vishnurchityala** [mavicompanion/BU-Notes#22]
![image](https://github.com/user-attachments/assets/71ac4e50-83ac-4108-a16a-f006b0e8ee23)

A responsive search box and app buttons can be created using Flexbox or Grid. The HTML structure includes a search container and an app buttons container. CSS styles ensure the layout adapts to different screen sizes. The search box has a text input and a button, while the app buttons provide access to settings and other quick links.

**Comment by Gyaanendra** [comment]
resolved it in the pull request  Gyaanendra:NewSearchBarAndProfile
