### ISSUE TITLE
Correct Favourite tiles alignment.

### ISSUE THREAD

**Issue by vishnurchityala** [mavicompanion/BU-Notes#23]
![image](https://github.com/user-attachments/assets/a337e2d4-6798-4cf3-a64e-f6f36d664a39)

The favorite tiles on the device are not aligned or sized correctly for larger screens, such as iPads.

**Comment by Gyaanendra** [comment]
ok

**Comment by Gyaanendra** [comment]
just commited a pr for the issues

**Comment by vishnurchityala** [comment]
Thank You buddy for the contribution, would love to see more contribution from your side.
