### ISSUE TITLE
Changing layout button.

### ISSUE THREAD

**Issue by vishnurchityala** [mavicompanion/BU-Notes#46]
### Existing Button

![image](https://github.com/user-attachments/assets/dedca3a3-1358-4960-bdc2-d90b08f25d25)

### To Create

![image](https://github.com/user-attachments/assets/4a54a71b-7dff-4399-9c40-b98469d92241)

#### Use of JS and simple CSS.

**Comment by TrueCoderSja** [comment]
I am working on it. Please assign the issue to me.

**Comment by TrueCoderSja** [comment]
This icon is only to be updated in first year. Right?

**Comment by TrueCoderSja** [comment]
Is this icon only to be updated in first year page or any other page too?

**Comment by vishnurchityala** [comment]
> Is this icon only to be updated in first year page or any other page too?

Just update in a single page first
