### ISSUE TITLE
Current Storage component

### ISSUE THREAD

**Issue by vishnurchityala** [mavicompanion/BU-Notes#48]
![image](https://github.com/user-attachments/assets/54291e7a-d558-4d6c-8d59-77725de00b45)

#### Add a storage component to the bottom of the sidebar, displaying the maximum number of allowable file uploads and the current status of ongoing uploads.

**Comment by CoderFleet** [comment]
Hi! Can I have this assigned to me please

**Comment by vishnurchityala** [comment]
Sorry for the late assignment.. you can do it now.

**Comment by CoderFleet** [comment]
Thanks For Assignment... 
Working on It
I had one query: will this count in Hacktoberfest?

Thanks

**Comment by CoderFleet** [comment]
@vishnurchityala Please Verify it

**Comment by CoderFleet** [comment]
@vishnurchityala  Hi! I have a little request...
Can you please add hactoberfest tag to repo and hactoberfest-accepted to the merged PR that will enable this to be considered on my hacktoberfest dashboard

Thanks
